version: "3.9"

services:
  web:
    build: .
    command: bash -c "python project/manage.py makemigrations image_api && python project/manage.py migrate && python project/manage.py loaddata db.json && python project/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
